### ISSUE TITLE
[BUG] Sometimes generates lessons that only introduce one character instead of 2

### ISSUE THREAD

**Issue by Beethoven-n** [BarbieCue/ktgen#278]
i'm not quite sure how to fix this on my own, but i'm trying to generate a lesson for the Workman layout.
my command is `ktgen /usr/share/ktouch/keyboardlayouts/us.workman.xml specs.txt --text-file 4000-most-common-english-words.csv`, using [this version of us.workman.xml (renamed so it'd actually upload here),](https://github.com/user-attachments/files/15755556/us.workman.xml.txt) a `specs.txt` that looks like this: `tn he so gy ai`, and [dictionary sourced from here.](https://github.com/pkLazer/password_rank/blob/master/4000-most-common-english-words-csv.csv)

for some reason, run like this, it generates an `i` lesson among the others that only features one new character:
```xml
     <lesson>
       <id>19c77ded-f559-4094-8842-6c2267de03be</id>
       <title>7: i</title>
       <newCharacters>i</newCharacters>
       <text>iii iii iii iii iii iii iii iii iii iii iii iii iii
 iii ii ii ii ii ii ii ii ii ii ii ii ii ii ii ii ii
 ii ii ii ii ii iiii iiii iiii iiii iiii iiii iiii
 iiii iiii iiii ii i i i i i i i i i i i i i i i i
 i i i i i i i i i i i i i i i i i i i i i i i i i
 i iii iii iii iii iii iii iii iii iii iii iii iii
 iii iii iiii iiii iiii iiii iiii iiii iiii iiii iiii
 iiii ii iii iii iii iii iii iii iii iii iii iii iii
 iii iii iii iii iii</text>
     </lesson>
```

what do?

**Comment by Beethoven-n** [comment]
gonna close this on my own. this is just what happens when you don't use a lesson specification. if anyone else happens to run into this problem, use the lesson_specifications.ktgen file from this repo like so:
`ktgen lesson_specifications.ktgen /usr/share/ktouch/keyboardlayouts/us.workman.xml --text-file 4000-most-common-english-words.csv -min 2`

**Comment by BarbieCue** [comment]
Hi @Beethoven-n and thanks for this report. I did not take a closer look now but i think the iiii lesson can be a result of the keyboard algorithm. It can be that the algorithm can not find a partner key for the i-key.

I'll take a closer look if i find some time.
